
#https://github.com/weaveworks/build-tools/blob/master/socks/connect.sh
---
apiVersion: v1
kind: Pod
metadata:
  name: task
  namespace: catapult
spec:
  containers:
    - name: task
      image: splatform/catapult
      command: ["/bin/bash"]
      imagePullPolicy: Always
      args: ["-c", "while true; do sleep 50000;done"]

      