#https://github.com/weaveworks/build-tools/blob/master/socks/connect.sh
---
apiVersion: v1
kind: Pod
metadata:
  name: task
  namespace: catapult
spec:
  containers:
    - name: task
      image: splatform/catapult
      command: ["/bin/bash"]
      imagePullPolicy: Always
      args: ["-c", "while true; do sleep 50000;done"]
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: dind-daemon
      image: docker:1.12.6-dind
      resources:
          requests:
              cpu: 20m
              memory: 512Mi
      securityContext:
          privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
